<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterDataBankRegis;

class MasterDataBankRegisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate existing data to start fresh
        MasterDataBankRegis::truncate();

        $banks = [
            'ACEH SYARIAH',
            'ALADIN SYARIAH',
            'ALLO BANK',
            'ALTOREM/PAY',
            'AMAR INDONESIA',
            'ANZ INDONESIA',
            'ARTAJASA PEMBAYARAN ELEK. (RTGS)',
            'ARTHA GRAHA',
            'ATMBPLUS',
            'ATMI',
            'BALI',
            'BANK BPD DIY UUS',
            'BANK CIMB NIAGA UUS',
            'BANK DANAMON UUS',
            'BANK DBS',
            'BANK DKI UUS',
            'BANK JAGO',
            'BANK JAGO UUS',
            'BANK JATENG UUS',
            'BANK JATIM - UUS',
            'BANK JOMBANG',
            'BANK MAYBANK UUS',
            'BANK MEGA SYARIAH',
            'BANK MIZUHO',
            'BANK NAGARI - UUS',
            'BANK NEO COMMERCE',
            'BANK OCBC NISP - UUS',
            'BANK PERMATA UUS',
            'BANK RAYA',
            'BANK RESONA',
            'BANK SAQU',
            'BANK SMBC',
            'BANK SULSELBAR UUS',
            'BANK SYARIAH NASIONAL',
            'BANTEN',
            'BCA SYARIAH',
            'BENGKULU',
            'BI',
            'BI CABANG AMBON,AMB',
            'BI CABANG BALIKPAPAN,BLP',
            'BI CABANG BANDA ACEH.BDA',
            'BI CABANG BANDAR LAMPUNG,BDL',
            'BI CABANG BANDUNG,BDG',
            'BI CABANG BANJARMASIN',
            'BI CABANG BATAM, BTM',
            'BI CABANG BENGKULU',
            'BI CABANG CIREBON,CRB',
            'BI CABANG DENPASAR,BALI',
            'BI CABANG GORONTALO',
            'BI CABANG JAMBI',
            'BI CABANG JAYAPURA',
            'BI CABANG JEMBER,JBR',
            'BI CABANG KEDIRI,KDR',
            'BI CABANG KENDARI,KDI',
            'BI CABANG KUPANG,KPG',
            'BI CABANG LHOKSEUMAWE,LSM',
            'BI CABANG MALANG, MLG',
            'BI CABANG MANADO,MDO',
            'BI CABANG MATARAM,CKA',
            'BI CABANG MEDAN,MDN',
            'BI CABANG PADANG,PDG',
            'BI CABANG PALANGKARAYA',
            'BI CABANG PALEMBANG,PLG',
            'BI CABANG PALU,PLS',
            'BI CABANG PANGKAL PINANG',
            'BI CABANG PEKAN BARU,PKB',
            'BI CABANG PONTIANAK,PTK',
            'BI CABANG SAMARINDA,SMD',
            'BI CABANG SEMARANG,SMG',
            'BI CABANG SERANG',
            'BI CABANG SIBOLGA',
            'BI CABANG SOLO,SLO',
            'BI CABANG SURABAYA,SBY',
            'BI CABANG TARAKAN',
            'BI CABANG TEGAL',
            'BI CABANG TERNATE',
            'BI CABANG UJUNG PANDANG',
            'BI CABANG YOGYAKARTA,YOG',
            'BI MAMUJU',
            'BI MANOKWARI',
            'BI PEMATANG SIANTAR',
            'BI PURWOKERTO,PWT',
            'BI TASIKMALAYA,TSM',
            'BJB',
            'BJB SYARIAH',
            'BLU BY BCA DIGITAL',
            'BMRI-BPR',
            'BNI',
            'BNP PARIBAS',
            'BOA',
            'BOC INDONESIA',
            'BOIINDONESIA',
            'BPD DIY',
            'BPD KALBAR UUS',
            'BPD KALSEL UUS',
            'BPD KALTIMTARA UUS',
            'BPD SUMSEL BABEL UUS',
            'BPD SUMUT UUS',
            'CITIBANK',
            'CTBC INDONESIA',
            'DANA',
            'DANAMON',
            'DEUTSCHE BANK',
            'DOKU',
            'FINNET INDONESIA (RTGS)',
            'GANESHA',
            'HIBANK DH MAYORA',
            'HSBC',
            'IBK BANK',
            'ICBC',
            'INA PERDANA',
            'INDEX',
            'INDONESIA EXIMBANK (RTGS)',
            'JAKARTA',
            'JALIN PEMBAYARAN NUSANTARA (JALIN)',
            'JAMBI',
            'JATENG',
            'JATIM',
            'JPMORGAN BANK',
            'JTRUST BANK',
            'KALBAR',
            'KALSEL',
            'KALTENG',
            'KALTIMKALTARA',
            'KB BANK',
            'KB BUKOPIN SYARIAH',
            'KEB HANA',
            'KROM',
            'KSEI',
            'LAMPUNG',
            'LEMBAGA PENJAMIN SIMPANAN',
            'MALUKUMALUT',
            'MANDIRI',
            'MANDIRI TASPEN',
            'MAS',
            'MASPION',
            'MAYAPADA',
            'MAYBANK (D/H BII)',
            'MEGA',
            'MESTIKA',
            'MNC BANK',
            'MUAMALAT',
            'MUFG BANK, LTD',
            'NAGARI',
            'NANO BANK',
            'NOBU',
            'NTB SYARIAH',
            'NTT',
            'OCBC',
            'OKE',
            'PANIN',
            'PANIN SYARIAH',
            'PAPUA',
            'PAYPRO',
            'PERMATA',
            'PT ALTO NETWORK (PT ALTO)',
            'PT PENYELESAIAN TRANSAKSI',
            'PT RINTIS SEJAHTERA (PT RINTIS)',
            'PT. BPD JAMBI UUS',
            'QNB INDONESIA',
            'SAHABAT SAMPOERN',
            'SBI INDONESIA',
            'SEABANK',
            'SHINHAN',
            'SHOPEEPAY',
            'SINARMAS',
            'SLEMAN',
            'STANDARD CHARTERED',
            'SULSELBAR',
            'SULTENG',
            'SULTRA',
            'SUMSELBABEL',
            'SUMUT',
            'SUPERBANK',
            'TCASH',
            'TELKOM',
            'UOB',
            'VICTORIA',
            'WOORI SAUDARA',
            'YOOPAY',
        ];

        foreach ($banks as $bankName) {
            MasterDataBankRegis::create([
                'nama_bank' => $bankName,
                'status' => true
            ]);
        }
    }
}
